
/*
 * action 类型
 */
export const FETCH_ACTIVITY_TYPE = 'FETCH_ACTIVITY_TYPE'
export const FETCH_ACTIVITY_LIST = 'FETCH_ACTIVITY_LIST'
export const SET_FILTER_CONFIG = 'SET_FILTER_CONFIG'
export const SET_TYPE = 'SET_TYPE'
export const TOGGLE_FILTER = 'TOGGLE_FILTER'
export const OPEN_DETAILS = 'OPEN_DETAILS'
export const FETCH_GET_TAGS = 'FETCH_GET_TAGS'
export const FETCH_GET_REWARD_OVERVIEW = 'FETCH_GET_REWARD_OVERVIEW'
export const FETCH_GET_REWARD_DETAILS = 'FETCH_GET_REWARD_DETAILS'
export const FETCH_GET_REWARD_GROUP = 'FETCH_GET_REWARD_GROUP'
export const SET_DRIVER_LIST_AND_TAG = 'SET_DRIVER_LIST_AND_TAG'
export const DRIVER_OR_ORDER = 'DRIVER_OR_ORDER'
export const SET_TIME_BY_DRIVER = 'SET_TIME_BY_DRIVER'
export const FETCHG_GET_REWARD_OVERVIEW = 'FETCHG_GET_REWARD_OVERVIEW'
